return {
	-- Code outline plugin.
	"hedyhli/outline.nvim",
	lazy = true,
	cmd = { "Outline", "OutlineOpen" },
	keys = {
		{ "<leader>o", "<cmd>OutlineClose<cr><cmd>Outline<cr>", desc = "Toggle outline" },
	},
	opts = {
		symbol_folding = {
			markers = { ">", "v" },
		},
		symbols = {
			icons = {
				File = { icon = "1", hl = "Identifier" },
				Module = { icon = "⧉", hl = "Include" },
				Namespace = { icon = "✇", hl = "Include" },
				Package = { icon = "4", hl = "Include" },
				Class = { icon = "𝓒", hl = "Type" },
				Method = { icon = "ƒ", hl = "Function" },
				Property = { icon = "5", hl = "Identifier" },
				Field = { icon = "", hl = "Identifier" },
				Constructor = { icon = "", hl = "Special" },
				Enum = { icon = "ℰ", hl = "Type" },
				Interface = { icon = "7", hl = "Type" },
				Function = { icon = "ƒ", hl = "Function" },
				Variable = { icon = "🗲", hl = "Variable" },
				Constant = { icon = "#", hl = "Constant" },
				String = { icon = "𝓐", hl = "String" },
				Number = { icon = "#", hl = "Number" },
				Boolean = { icon = "⊨", hl = "Boolean" },
				Array = { icon = "10", hl = "Constant" },
				Object = { icon = "⦿", hl = "Type" },
				Key = { icon = "🔐", hl = "Type" },
				Null = { icon = "NULL", hl = "Type" },
				EnumMember = { icon = "", hl = "Identifier" },
				Struct = { icon = "𝓢", hl = "Structure" },
				Event = { icon = "🗲", hl = "Type" },
				Operator = { icon = "+", hl = "Identifier" },
				TypeParameter = { icon = "𝙏", hl = "Identifier" },
				Component = { icon = "11", hl = "Function" },
				Fragment = { icon = "12 ", hl = "Constant" },
				TypeAlias = { icon = "13 ", hl = "Type" },
				Parameter = { icon = "14 ", hl = "Identifier" },
				StaticMethod = { icon = "15 ", hl = "Function" },
				Macro = { icon = " ", hl = "Function" },
			},
		},
	},
}
